jwt:
    get:
        token:
            uri: /authenticate
    http:
        request:
            header: Authorization
    refresh:
        token:
            uri: /refresh
    signing:
        key:
            secret: mySecret
    token:
        expiration:
            in:
                seconds: 604800000
server:
    port: 8081
spring:
    datasource:
        driver-class-name: com.mysql.cj.jdbc.Driver
        hikari:
            connectionTimeout: 30000
            idleTimeout: 30000
            maxLifetime: 2000000
            maximumPoolSize: 100
            minimumIdle: 5
            poolName: DBCP
        password: ''
        url: jdbc:mysql://localhost:3306/ecom_medicine
        username: root
    jpa:
        database: mysql
        hibernate:
            ddl-auto: update
        open-in-view: false
        properties:
            hibernate:
                dialect: org.hibernate.dialect.MySQL5Dialect
        show-sql: true

##Comments -- Added for test CI/CD
##Comments -- Added for test CI/CD with Docker Image Creation and Push to Dockerhub